#settings for SleepingServerStarter

serverName: Server adormecido, tente conectar para acorda-lo1
serverPort: 25565
loginMessage: Acordando server, tente reconectar em 1 minuto
serverOnlineMode: true

webPort: 0	 					# 0 to disable web hosting, 8123default dynmap
webDir: plugins/dynmap/web 	# dir of dynmap web

startMinecraft: 1 				# 0 to disable	
minecraftCommand: java -jar craftbukkit-1.16.4.jar nogui

